# Generated by Django 4.0.1 on 2022-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_price', models.PositiveIntegerField(verbose_name='Цена')),
                ('card_descript', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_title', models.CharField(max_length=200, verbose_name='Услуга')),
                ('table_old_price', models.PositiveIntegerField(verbose_name='Старая Цена')),
                ('table_new_price', models.PositiveIntegerField(verbose_name='Новая Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
