# Generated by Django 4.0.1 on 2022-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='slider_img/', verbose_name='Изображение')),
                ('slider_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slider_text', models.CharField(max_length=200, verbose_name='Текст')),
                ('slider_css', models.CharField(blank=True, default='-', max_length=200)),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
