# Generated by Django 4.0.1 on 2022-01-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='slider_css',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='CSS Класс'),
        ),
    ]
